### ISSUE TITLE
Search query with facets?

### ISSUE THREAD

**Issue by wilkinj33** [inonit/drf-haystack#114]
Current have '/api/search/facets/' working correctly, as I am faceting on retailers stores for a large list of items. 
serializers.py 

    class HaystackFacetSerializer(HaystackFacetSerializer):
	    serialize_objects = True
	
	class Meta:
		index_classes = [ItemIndex]	
		fields = ['retailer']
		field_options = {
				'retailer': {}
			}
		
    class HaystackSerializer(HaystackSerializer):
	    class Meta:
		     index_classes = [ItemIndex]	
		     fields = ['text', 'title', 'price', 'url', 'retailer', 'image']

I'm unable to to figure out how to still have my basic search functions such as /'api/search/title=blue jeans'. I want to be able to make a request like that and then have the option to facet by retailers. Any thoughts? 

If I make search such as '/api/search/facets/?selected_facets=retailer_exact:retailer&title=blue jeans' all items are still returned. The search function doesn't work.

Thanks

**Comment by rhblind** [comment]
Hi, unfortunately faceting doesn't work exactly like that out of the box in haystack itself, and drf-haystack is built upon that, so it's the same for us.
It is mentioned in the [docs](https://drf-haystack.readthedocs.io/en/latest/07_faceting.html#serializing-faceted-counts) (in the Tip box), but not very detailed.

Basically you'd have to do some customization so that you can pass an already filtered queryset into the faceting filter [here](https://github.com/inonit/drf-haystack/blob/master/drf_haystack/mixins.py#L52).

**Comment by wilkinj33** [comment]
That's great. Thank you, I'll look into it and post my outcome.

**Comment by rhblind** [comment]
Can I close this?

**Comment by ehmadzubair** [comment]
@rhblind I've read the tooltip that you've mentioned in the above comments and this is exactly what i thought. However, i've tried it on my dataset and `SearchQuerySet` seems to work as follows:

Without Filter
```
>>> sqs = SearchQuerySet().facet('category')
>>> sqs.facet_counts()
{'fields': {'category': [('Pret > Formal', 1), ('Unstitched > Basic', 1)]}, 'dates': {}, 'queries': {}}
```

With Filter
```
>>> sqs = SearchQuerySet().filter(title__like='red').facet('category')
>>> sqs.facet_counts()
{'fields': {'category': [('Pret > Formal', 1)]}, 'dates': {}, 'queries': {}}
```

Am i missing something here?

**Comment by rhblind** [comment]
@ehmadzubair Hm, that's a bit unexpected. Not quite sure what's going on here, but it might be that something has changed upstream in django-haystack...
