### ISSUE TITLE
Using filters disables search

### ISSUE THREAD

**Issue by enkitosh** [inonit/drf-haystack#20]
I'm trying to get search results of images ordered by the time they were uploaded. But when I apply filters as usually with django rest framework I loose the ability to search. This is expected behaviour? Is there a way around this?

Code

    class ImageModelGeneralSerializer(HaystackSerializer):
        class Meta:
            index_classes = [ImageModelGeneralIndex]
            fields = ['id', 'uploaded_at', 'created_by','image', 'caption', 'photographer']

    class ImageSearchView(HaystackViewSet):
        index_models = [ImageModelGeneral]
        serializer_class = ImageModelGeneralSerializer
        filter_backends = (OrderingFilter,)
        ordering_fields = ('uploaded_at')
        ordering = ('-uploaded_at')

**Comment by rhblind** [comment]
Hi,
Well, you can't apply regular filters on a view which inherits from `HaystackViewSet`, because the data source is a `SearchQuerySet` and not a regular `QuerySet`.
The default filter for `HaystackViewSet` is `drf_haystack.filters.HaystackFilter`, so if you need to do some custom filtering for your view, I suggest you subclass from that when you build your `OrderingFilter`.

Take a look at the docs if you haven't =)

**Comment by enkitosh** [comment]
Ahh ok of course, I see it now, Advanced Usage. Sorry about that, I was a bit too quick.
Thank you for your response, it was very helpful :+1:

**Comment by rhblind** [comment]
No problem, glad I could help =)
