### ISSUE TITLE
Remove elasticsearch from requirements.txt

### ISSUE THREAD

**Issue by moshthepitt** [inonit/drf-haystack#33]
It is not needed if one is not using elasticsearch

**Comment by rhblind** [comment]
Hehe, good catch! ;)

**Comment by rhblind** [comment]
Well, I take it you meant from `install_requires`in `setup.py`.
Having `elasticsearch` in `requirements.txt` is fine, because that's what I use for development, and some tests are dependent on it. When installing the package only what's specified in `setup.py` file is installed.

I'll remove it from there.
