### ISSUE TITLE
Serialize QuerySet, not SearchQuerySet?

### ISSUE THREAD

**Issue by LennyLip** [inonit/drf-haystack#36]
May be is not drf-haystack issue, but i want to ask.

I want just to filter QuerySet with "?q=bla bla bla"  params (using elastixsearch via haystack anyway).

I see in code https://github.com/inonit/drf-haystack/blob/master/drf_haystack/serializers.py#L37 and
```
    # NOTE: Make sure you don't confuse these with model attributes. These
    # fields belong to the search index!
```

that we have mapping haystack_fields in serializer and etc. May be it is good for something, but redundancy in my case.

I just need - search by query q param and return filtered QuerySet.

More over, i use django-filter backend to filter queryset http://www.django-rest-framework.org/api-guide/filtering/#djangofilterbackend and i want to combine filter result with haystack results (for one Model). 

May me i must use somthing like this (not tested!):  
http://django-haystack.readthedocs.org/en/latest/searchqueryset_api.html#load-all-queryset

drf view:

```
def queryset_gen(search_qs):
    for item in search_qs:
        yield item.object  

def get(self, request, format=None):
        # foo from GET q
        sqs = RelatedSearchQuerySet().filter(content='foo').load_all()
        # For the Entry model, we want to include related models directly associated
        # with the Entry to save on DB queries.
        sqs = sqs.load_all_queryset(Entry, self.queryset.select_related(depth=1))
        self.queryset = queryset_gen(sqs)
 
       return self.list(request, *args, **kwargs)
```

or it is wrong way and i can make it better with drf-haystack ?

**Comment by rhblind** [comment]
Hi,
Sorry for late response, I've been a bit busy lately.

I'm not quite sure that I understand the question completely? If you want to perform search and filtering on a normal django `QuerySet`, you should not be using `drf_haystack` for this. `django-filter` is a better choice for doing custom filters on regular django querysets.

If you want to filter on a haystack `SearchQuerySet` , `drf_haystack` is a good choice. You can set up field aliases in order to perform `?q=bla bla bla` queries (see the [Autocomplete example](http://drf-haystack.readthedocs.org/en/latest/advanced_usage.html#autocomplete) in the docs).

If you need to merge results from a regular `QuerySet` and a `SearchQuerySet`, you need to sort it out manually, there's no included functionality for such use cases. Seems like you're already on the right track ;)

Hope this made sense?

**Comment by LennyLip** [comment]
Thanks, @rhblind , i just need "normal django QuerySet" with Full Text Search. 
Finally, i've been start to use posgtres FTS. Now, i can use FTS query attached directlly to django SQL queries, without serialize\deserialize objects to other search engine DB (f.e., elasticsearch) or ugly merge by ids.
