### ISSUE TITLE
How to render object data instead of index data?

### ISSUE THREAD

**Issue by madEng84** [inonit/drf-haystack#44]
As you can read in the title, this is not a bug, but i need a representation of my data without launching update_index.
Is it possible?
If so (i hope that), The documentation is incomplete

> class LocationSerializer(HaystackSerializer):

    class Meta:
        # The `index_classes` attribute is a list of which search indexes
        # we want to include in the search.
        index_classes = [LocationIndex]

        # The `fields` contains all the fields we want to include.
        # NOTE: Make sure you don't confuse these with model attributes. These
        # fields belong to the search index!
        fields = [
            "text", "address", "city", "zip_code", "autocomplete"
        ]

**Comment by rhblind** [comment]
Hi,
You can use the [HaystackSerializerMixin](https://github.com/inonit/drf-haystack/blob/master/drf_haystack/serializers.py#L359) which will render the instance's database object. Note that this will perform a query to the database.

**Comment by madEng84** [comment]
Thank you @rhblind,
Unfortunately i see this error:

> 'BlogEntry' object has no attribute 'searchindex'

where BlogEntry is the model associated with one of my search_indexes

`class BlogAndFaqEntryHaystackSerializer(HaystackSerializerMixin, 
                             HaystackSerializer):

    class Meta:
        # The `index_classes` attribute is a list of which search indexes
        # we want to include in the search.
        index_classes = [BlogEntry,FaqEntry]

        # The `fields` contains all the fields we want to include.
        # NOTE: Make sure you don't confuse these with model attributes. These
        # fields belong to the search index!
        ##### Inheriting from HaystackSerializerMixin, I have to insert model attributes?? Is it right? ####
        fields = [
            #"text", 
            "title", "city", 
            "publication_start", "location",
        ]`

 Inheriting from HaystackSerializerMixin, I have to insert model attributes?? Is it right?

Any help is appreciated

**Comment by rhblind** [comment]
Hi, sorry for delayed response!

No, the `fields` class attribute should contain fields from your HaystackIndex class. They are used in order to construct the query.

The `drf-haystack` library is written to serialize haystack indices, so if you just want to render your database object, you probably should just use a normal django rest framework view.
The `HaystackSerializerMixin` class mentioned above just replaces the `obj` attribute with `instance.object` in the `to_representation()` method. It's really just a hack/convenience in order to do filtering using Haystack and serialize the database representation of that object. It *will* cause you to hit the database.
Once you have your `instance.object` object, you are free to return whatever data you wish from this method.

If this is not what you're asking for, then I'm afraid I don't really understand what your're asking for?
