### ISSUE TITLE
Excluding document field from serializer

### ISSUE THREAD

**Issue by jrief** [inonit/drf-haystack#7]
In ``HaystackFilter.build_filter`` there is a check to “Skip if the parameter is not listed in the serializer's `fields` or if it's in the `exclude` list.”

In my current project, this causes some trouble. My SearchIndex class has the usual field ``text = indexes.CharField(document=True, use_template=True)`` and a bunch of other fields. This ``text`` field holds the index used for searching, while the other fields only contain data to be rendered when displaying the result list. Now, it doesn't make much sense to serialize this ``text`` field and send it to the client, because the result list has no usage for it. Moreover, this field is quite large and thus increases the Ajax payload needlessly.

A workaround would be to add a method ``to_representation`` to my SearchSerializer class and remove that ``text`` field from the result, but then it has already been serialized.

Therefore I'd like to know if there is any special reason for this check, and/or if You/I shall remove this check or add a kind of "ignore" field for this purpose to the serializer class?

BTW, many thanks for this great library.

**Comment by rhblind** [comment]
Hi Jacob!
My pleasures, glad you find it useful =)

There are two reasons for this check. 
It allows you to have one index with multiple entry points, each with access to different fields in the index.

Secondly, I want this library to act as close to DRF as possible, so that people already familiar with DRF feels right at home. So this check hooks into the `Serializer.Meta.fields` and `Serializer.Meta.exclude` lists.

The workaround you propose will probably work in most cases, but serializing the `text` field could be expensive sometimes, so it might be a good idea with some kind of "ignore_field_serialize" attribute.

My initial thoughts are that this might be something to look into, but I've got one suggestion for you first.
On your `HaystackSerializer` class, you should be able to do something like this.

     class MySerializer(HaystackSerializer):

        text = SerializerMethodField()

        class Meta:
            fields = ["text", "firstname", "lastname"]

        def get_text(self, obj):
            return None

This will prevent rendering serializing the field, but instead return None for the value. Since the `text` attribute still exists in the `fields` list, it will be picked up and filtered on, so you should get correct results.
This will of course render a `text: null` field in the json response, but you might also remove that in the `to_representation` method.
I realize that this is probably not super-slick, but at least it will provide you with your desired results.

If you have a good idea on a generic way to implement your suggestion, I will of course be happy to take a look at it =)

Cheers

**Comment by jrief** [comment]
Now I applied the above trick. It does the job, but is somehow a hack.
Anyway, since ``field_aliases `` is a field name in ``Meta`` which is not part of the DRF ecosystem, why not use a similar field name for this purpose, say ``fields_ignore_serialize``?
If you agree, I could create a PR for this.

**Comment by rhblind** [comment]
Yes, I totally agree, it's somewhat a hack.

Also, I have been thinking a bit about this. I'm almost tempted to exclude the `document=True` field serialization by default as you initially suggested, and then have an `include_document_field=True` (or similar) on the `Meta` class (or similar) to include it in the result.
As you said, this field is rarely of interest for the client.

This is based on the assumption that each index class can have only one `document=True` field (which I believe is the case).

What do you think?

And, yes, I would be delighted for a pull request ;)

**Comment by rhblind** [comment]
This should be quite easy to implement in `HaystackSerializer.get_fields()`

**Comment by jrief** [comment]
I currently use two indices, one is our well known ``text = indexes.CharField(document=True, use_template=True)`` fields, the other is ``autocomplete = indexes.EdgeNgramField(use_template=True)``.
For the client, both these fields do not make sense, but only one can be ``document=True``. Therefore, an explicit list might make more sense.

**Comment by rhblind** [comment]
Alright, I agree.
It's also more flexible as others might have other use cases.

**Comment by rhblind** [comment]
Hi again Jacob.
I'll have to ship a new version soon (because django-haystack has fixed an issue which I have a rather nasty workaround for), in order to be compatible with latest django-haystack release.

If you would like to have your `ignore_serialization` feature in it, I can wait for a few days, but not much longer.
