### ISSUE TITLE
Field warning is noisy

### ISSUE THREAD

**Issue by clintonb** [inonit/drf-haystack#77]
This warning is quite noisy for me:

> "Field '{field}' already exists in the field list. This *will* overwrite existing field '{field}'"

It is implemented at https://github.com/inonit/drf-haystack/blob/a0cb22fe883079a96eced59e6f3cf658b0b6a5be/drf_haystack/serializers.py#L213-L214.

I consider this warning noise because it's warning about a standard pattern in DRF serializers. The the serializer below. When I run code that uses this serializer, the warning is warning me of the fact that my `SerializerMethodField` will be used instead of the default field. This pattern of overriding the field is common, and necessary in some cases, for DRF projects.

```python
class ProgramSearchSerializer(HaystackSerializer):
    authoring_organizations = serializers.SerializerMethodField()

    def get_authoring_organizations(self, program):
        organizations = program.authoring_organization_bodies
        return [json.loads(organization) for organization in organizations] if organizations else []

    class Meta:
        field_options = {}
        fields = ('uuid', 'authoring_organizations', )
        index_classes = [ProgramIndex]
```
Is there a specific reason for these warnings? If not, I propose removing them or, at least, providing the option to disable them.

**Comment by rhblind** [comment]
Hi, yeah I kind of agree.
The reason (if I remember correctly) was in cases where there is multiple indices being serialized, in order to help users figure out why the outputted fields contain other information than they might have expected.
But you are correct, this is a standard pattern for DRF, it's only that it is being automated here in some cases.

Feel free to submit a PR with the removal. We can add a little heads up in the docs instead...

**Comment by clintonb** [comment]
@rhblind please let me know when you'll be able to release a new version/RC.

**Comment by rhblind** [comment]
I'll try to get it done by the weekend or so.
