### ISSUE TITLE
HaystackGenericAPIView. get_queryset evaluates the queryset

### ISSUE THREAD

**Issue by amit5148** [inonit/drf-haystack#86]
The code **if self.quesyset** in [generics.py:48](https://github.com/inonit/drf-haystack/blob/master/drf_haystack/generics.py#L48) results in the queryset being evaluated by django.
Is this behaviour intentional?

**Comment by rhblind** [comment]
Hi, thanks for reporting.
Hm, no it's not really intentional. It seems like this test resides from the early days of the library and could probably be rewritten to something better. I don't really think the **isinstance()** test is required anymore either, since nothing would really work if it's not a `SearchQuerySet` instance.
You are probably right about the evaluation on truth testing, but I'm not really sure actually. Remember this is really a haystack `SearchQuerySet` instance and not a django `queryset`. Anyway, the API is quite similar, so you are probably right =)

Anyway it should be looked into and fixed.

**Comment by rhblind** [comment]
Fixed by #88
