### ISSUE TITLE
Does django need to be included?

### ISSUE THREAD

**Issue by naglalakk** [inonit/drf-haystack#98]
Hey. First of all, thank you so much for your fantastic library. 

I'm wondering why you include Django in the setup.py file. I understand that the versions of drf-haystack follow the django versions but this means if I have for example django==1.10.6 this package will uninstall that version of django and install django==1.11. Is this necessary?

**Comment by rhblind** [comment]
Hello, thank you for your kind words!

The reason Django is in the `install_requires`section is to make it automatically install a supported version if Django is not installed.
It should however, not uninstall your existing Django version if it's within the required version range.

Now, there's been a while since I've had time to do maintenance on the library, and Django so I'll try to have a look at it soonish.

**Comment by rhblind** [comment]
Hi, small update here.
Strictly speaking, it does not need to be included, but ususally django is being updated faster  than `django-haystack` which we rely on. Therefore I need to be able to lock down supported django versions in order to be sure to be compatible.

**Comment by naglalakk** [comment]
Hey @rhblind totally, understood. I actually see that haystack does this as well and the reason has become more clear then when I asked the question. Django is now at 2.0. Not locking down the version could install a newer verison of django which is inconsistent with the current version of drf-haystack. Thank you for clearing this up 👍
